declare const __GATEY_PREMIUM__: boolean;
declare const __OB_KEY_EXPR__: number;
declare const __OB_PARTS__: string[];
declare const __FETCH_EXPR__: string;
declare const __T_PARAM_EXPR__: string;
declare const __H_PARAM_EXPR__: string;
declare const __SITE_ID_EXPR__: string;
declare const __SUBSCRIBER_EXPR__: string;
declare const __LAST_UPDATE_EXPR__: string;
